// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1650810542);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1650810586);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{b36f2da6-62eb-4d19-803d-c74d81a4dfa3}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1650810512);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6aab3f47-1cad-4809-9136-da30de7ac1be}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"floorp-rss-read_mozilla_org\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\",\"floorp-system_floorp_ablaze_one\"],\"idsInUrlbar\":[\"floorp-rss-read_mozilla_org\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_\",\"floorp-system_floorp_ablaze_one\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220407234545");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220407234545");
user_pref("browser.startup.homepage_override.mstone", "99.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1650810662);
user_pref("browser.theme.toolbar-theme", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[\"treestyletab_piro_sakura_ne_jp-browser-action\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"floorp-undo-closed-tab_floorp_ablaze_one-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"floorp-undo-closed-tab_floorp_ablaze_one-browser-action\",\"treestyletab_piro_sakura_ne_jp-browser-action\",\"_036a55b4-5e72-4d05-a06c-cba2dfcc134a_-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"widget-overflow-fixed-list\",\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.iniFile.exists.appversion", "99.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1650810555);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220408000428");
user_pref("extensions.lastAppVersion", "99.0.1");
user_pref("extensions.lastPlatformVersion", "99.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.floorp-rss-read@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.floorp-system@floorp.ablaze.one", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.floorp-undo-closed-tab@floorp.ablaze.one", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.treestyletab@piro.sakura.ne.jp", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{036a55b4-5e72-4d05-a06c-cba2dfcc134a}", true);
user_pref("extensions.webextensions.uuids", "{\"floorp-rss-read@mozilla.org\":\"790b9f33-2be9-416d-94e1-28588471f11a\",\"floorp-system@floorp.ablaze.one\":\"54844750-d221-4477-9d24-3f467f7772f3\",\"floorp-undo-closed-tab@floorp.ablaze.one\":\"931e3102-ca6e-45f8-8c95-1aa25033258f\",\"formautofill@mozilla.org\":\"bc7f65e2-cc22-4610-b830-b4c252b41676\",\"pictureinpicture@mozilla.org\":\"e6dee65a-32a7-4c36-808a-6fc586462d43\",\"screenshots@mozilla.org\":\"89c02790-46ce-491a-b884-3faaf9eb279b\",\"treestyletab@piro.sakura.ne.jp\":\"a23a6946-6fce-4525-9a2e-a3a5cdc3df41\",\"webcompat-reporter@mozilla.org\":\"37947885-3784-4d7e-8dd5-34aa31d45710\",\"webcompat@mozilla.org\":\"270a6a88-85f1-450a-ac4c-863374e6bdce\",\"{036a55b4-5e72-4d05-a06c-cba2dfcc134a}\":\"33f05e94-673a-426b-a822-25a165a5741c\",\"default-theme@mozilla.org\":\"f476052a-7af8-44c8-8682-bd486ab0b081\",\"addons-search-detection@mozilla.com\":\"d00cc159-7f21-41e1-b993-6e7efc860a7f\",\"google@search.mozilla.org\":\"ecffe477-6cdd-40ad-a62e-bdef48b49ba5\",\"wikipedia@search.mozilla.org\":\"48943323-9213-443f-b5bc-913788adeafb\",\"bing@search.mozilla.org\":\"e514b72d-9c76-409d-bf00-bba1d5154195\",\"ddg@search.mozilla.org\":\"a2c1e800-3b56-4dfa-a9d1-04a1b5a82988\",\"yahoo-jp-auctions@search.mozilla.org\":\"d28faab6-2262-4fe7-8eb9-0ba8461ac81b\",\"rakuten@search.mozilla.org\":\"b011baad-c066-410b-98f8-697c1258b114\",\"yahoo-jp@search.mozilla.org\":\"c6fab98f-b7ac-40d5-b269-5d14600b401f\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1650810521);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.locale.requested", "ja,en-US");
user_pref("media.gmp-manager.buildID", "20220407234545");
user_pref("media.gmp-manager.lastCheck", 1650810615);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.extension", "treestyletab@piro.sakura.ne.jp");
user_pref("privacy.userContext.ui.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "56f28919-9ae1-471d-a94e-0ade091c7c81");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1650810660);
